sudo: required
language: generic
services: 
  - docker  

before_install:
  - docker build -t farhan/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true farhanhameed010/react-test npm run test -- --coveragae


after_success:
  - docker build -t farhanhameed010/multi-client ./client
  - docker build -t farhanhameed010/multi-nginx ./nginx
  - docker build -t farhanhameed010/multi-server ./server
  - docker build -t farhanhameed010/multi-worker ./worker

  # Log in to the docker CLI

- echo "$DOCKER_PS" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
- docker push farhanhameed010/multi-client 
- docker push farhanhameed010/multi-nginx 
- docker push farhanhameed010/multi-server 
- docker push farhanhameed010/multi-worker 